const demoResources = [
  {
    _id: '1',
    title: 'A Mini Course on Time Management',
    platform: 'Udemy',
    url: 'https://udemy.com/time-management',
    relatedSkills: ['productivity', 'time management', 'organization'],
    cost: 'Free',
    description: '7 steps you can use immediately to become more productive and master time management',
    instructor: 'Brandon Hakim, Insider School',
    rating: 4.4,
    reviews: 50088,
    students: 451964,
    duration: '0.5 total hours',
    lectures: 12,
    level: 'All Levels',
    thumbnail: 'purple',
    languages: ['English', 'Arabic', 'Spanish']
  },
  {
    _id: '2',
    title: 'Change Agility in the Workplace: Become a Change Agent',
    platform: 'Coursera',
    url: 'https://coursera.com/change-agility',
    relatedSkills: ['leadership', 'change management', 'agility'],
    cost: 'Free',
    description: 'Become an agent of change by adopting the agility and resilience skills required in the evolving modern workplace.',
    instructor: 'Shelley Osborne',
    rating: 4.5,
    reviews: 28726,
    students: 345892,
    duration: '1 total hour',
    lectures: 27,
    level: 'All Levels',
    thumbnail: 'teal',
    languages: ['English']
  },
  {
    _id: '3',
    title: 'Code Your First Game: Arcade Classic in JavaScript on Canvas',
    platform: 'YouTube',
    url: 'https://youtube.com/js-game',
    relatedSkills: ['javascript', 'html5', 'game development', 'canvas'],
    cost: 'Free',
    description: 'Program a complete game today. No special software or install required. All you need is a text editor and a web browser.',
    instructor: 'Chris DeLeon',
    rating: 4.5,
    reviews: 28638,
    students: 298473,
    duration: '2 total hours',
    lectures: 12,
    level: 'Beginner',
    thumbnail: 'orange',
    languages: ['English']
  },
  {
    _id: '4',
    title: 'How to speak to anyone & be fearless - in less than 55 min',
    platform: 'Udemy',
    url: 'https://udemy.com/public-speaking',
    relatedSkills: ['communication', 'public speaking', 'confidence'],
    cost: 'Free',
    description: 'Learn to quickly connect with crowds of strangers, be better on dates or ace that job interview.',
    instructor: 'Ricardo Mendoza',
    rating: 4.4,
    reviews: 24147,
    students: 187562,
    duration: '0.9 total hours',
    lectures: 8,
    level: 'All Levels',
    thumbnail: 'yellow',
    languages: ['English', 'Spanish']
  },
  {
    _id: '5',
    title: 'Complete Web Development Bootcamp',
    platform: 'Udemy',
    url: 'https://udemy.com/web-bootcamp',
    relatedSkills: ['html', 'css', 'javascript', 'react', 'node.js'],
    cost: 'Paid',
    description: 'Become a full-stack web developer with just one course. HTML, CSS, Javascript, Node, React, MongoDB and more!',
    instructor: 'Angela Yu',
    rating: 4.7,
    reviews: 98234,
    students: 567892,
    duration: '52 total hours',
    lectures: 156,
    level: 'Beginner',
    thumbnail: 'blue',
    languages: ['English']
  },
  {
    _id: '6',
    title: 'Python for Data Science and Machine Learning',
    platform: 'Coursera',
    url: 'https://coursera.com/python-ml',
    relatedSkills: ['python', 'data science', 'machine learning', 'pandas'],
    cost: 'Free',
    description: 'Learn how to use NumPy, Pandas, Seaborn, Matplotlib, Plotly, Scikit-Learn, Machine Learning, Tensorflow, and more!',
    instructor: 'Jose Portilla',
    rating: 4.6,
    reviews: 67234,
    students: 423156,
    duration: '25 total hours',
    lectures: 89,
    level: 'Intermediate',
    thumbnail: 'green',
    languages: ['English']
  },
  {
    _id: '7',
    title: 'Digital Marketing Masterclass',
    platform: 'Udemy',
    url: 'https://udemy.com/digital-marketing',
    relatedSkills: ['marketing', 'seo', 'social media', 'analytics'],
    cost: 'Paid',
    description: 'Master Digital Marketing Strategy, Social Media Marketing, SEO, YouTube, Email, Facebook Marketing, Analytics & More!',
    instructor: 'Phil Ebiner',
    rating: 4.5,
    reviews: 45678,
    students: 234567,
    duration: '23 total hours',
    lectures: 127,
    level: 'All Levels',
    thumbnail: 'purple',
    languages: ['English', 'Spanish']
  },
  {
    _id: '8',
    title: 'The Complete SQL Bootcamp',
    platform: 'Coursera',
    url: 'https://coursera.com/sql',
    relatedSkills: ['sql', 'database', 'postgresql', 'data analysis'],
    cost: 'Free',
    description: 'Become an expert at SQL! Learn to read and write complex queries to a database using PostgreSQL.',
    instructor: 'Jose Portilla',
    rating: 4.6,
    reviews: 56234,
    students: 389456,
    duration: '9 total hours',
    lectures: 43,
    level: 'Beginner',
    thumbnail: 'teal',
    languages: ['English']
  }
];
export { demoResources };