export const jobSeeds = [
  {
    title: "Frontend Developer Intern",
    company: "TechHive",
    location: "Remote",
    requiredSkills: ["javascript", "react", "html", "css"],
    recommendedExperience: "Fresher",
    jobType: "Internship",
    description: "Assist in building UI components and improving the user interface.",
    track: "Web Development",
    applyUrl: "",
    tags: ["react", "frontend", "internship"],
    createdBy: "seed"
  },
  {
    title: "Junior Backend Developer",
    company: "SoftCraft Solutions",
    location: "Dhaka",
    requiredSkills: ["node.js", "express", "mongodb"],
    recommendedExperience: "Junior",
    jobType: "Full-time",
    description: "Develop scalable backend APIs and database models.",
    track: "Web Development",
    applyUrl: "",
    tags: ["backend", "api", "javascript"],
    createdBy: "seed"
  },
  {
    title: "UI/UX Design Intern",
    company: "PixelForge Studio",
    location: "Remote",
    requiredSkills: ["figma", "ui/ux", "wireframing"],
    recommendedExperience: "Fresher",
    jobType: "Internship",
    description: "Support design team in creating wireframes and prototypes.",
    track: "Design",
    applyUrl: "",
    tags: ["design", "figma", "ui"],
    createdBy: "seed"
  },
  {
    title: "Data Analyst Intern",
    company: "Insight Analytics",
    location: "Chittagong",
    requiredSkills: ["excel", "sql", "data analysis"],
    recommendedExperience: "Fresher",
    jobType: "Internship",
    description: "Perform data cleaning and generate reports.",
    track: "Data",
    applyUrl: "",
    tags: ["data", "internship", "analysis"],
    createdBy: "seed"
  },
  {
    title: "Junior Data Scientist",
    company: "DataLab BD",
    location: "Remote",
    requiredSkills: ["python", "machine learning", "pandas"],
    recommendedExperience: "Junior",
    jobType: "Full-time",
    description: "Work on ML models, feature engineering, and data pipelines.",
    track: "Data",
    applyUrl: "",
    tags: ["data science", "python", "ml"],
    createdBy: "seed"
  },
  {
    title: "Mobile App Developer (Flutter)",
    company: "AppBuilders",
    location: "Dhaka",
    requiredSkills: ["flutter", "dart", "firebase"],
    recommendedExperience: "Junior",
    jobType: "Full-time",
    description: "Build cross-platform mobile applications.",
    track: "Mobile Development",
    applyUrl: "",
    tags: ["flutter", "mobile", "dart"],
    createdBy: "seed"
  },
  {
    title: "Cybersecurity Intern",
    company: "SecureNet",
    location: "Remote",
    requiredSkills: ["networking", "security basics", "linux"],
    recommendedExperience: "Fresher",
    jobType: "Internship",
    description: "Work with the security team to monitor vulnerabilities.",
    track: "Cybersecurity",
    applyUrl: "",
    tags: ["security", "cybersec", "internship"],
    createdBy: "seed"
  },
  {
    title: "DevOps Engineer (Junior)",
    company: "CloudSync",
    location: "Dhaka",
    requiredSkills: ["docker", "linux", "ci/cd"],
    recommendedExperience: "Junior",
    jobType: "Full-time",
    description: "Maintain deployment pipelines and cloud environments.",
    track: "DevOps",
    applyUrl: "",
    tags: ["devops", "docker", "cloud"],
    createdBy: "seed"
  },
  {
    title: "Full Stack Developer Intern",
    company: "CodeForge",
    location: "Remote",
    requiredSkills: ["javascript", "react", "node.js"],
    recommendedExperience: "Fresher",
    jobType: "Internship",
    description: "Assist in full-stack development projects.",
    track: "Web Development",
    applyUrl: "",
    tags: ["full stack", "javascript", "internship"],
    createdBy: "seed"
  },
  {
    title: "Junior QA Engineer",
    company: "QualityHub",
    location: "Dhaka",
    requiredSkills: ["testing", "selenium", "api testing"],
    recommendedExperience: "Junior",
    jobType: "Full-time",
    description: "Perform automated and manual testing across product modules.",
    track: "Quality Assurance",
    applyUrl: "",
    tags: ["qa", "testing", "automation"],
    createdBy: "seed"
  },
  {
    title: "Freelance Graphic Designer",
    company: "CreativeWorks",
    location: "Remote",
    requiredSkills: ["photoshop", "illustrator", "branding"],
    recommendedExperience: "Mid",
    jobType: "Freelance",
    description: "Design brand assets and marketing visuals for clients.",
    track: "Design",
    applyUrl: "",
    tags: ["design", "branding"],
    createdBy: "seed"
  },
  {
    title: "Part-time Content Writer",
    company: "StoryFlow",
    location: "Dhaka",
    requiredSkills: ["writing", "seo", "research"],
    recommendedExperience: "Fresher",
    jobType: "Part-time",
    description: "Write blogs, guides, and SEO-based content.",
    track: "Content Writing",
    applyUrl: "",
    tags: ["writing", "seo"],
    createdBy: "seed"
  },
  {
    title: "Junior Cloud Engineer",
    company: "SkyCloud Solutions",
    location: "Remote",
    requiredSkills: ["aws", "linux", "networking"],
    recommendedExperience: "Junior",
    jobType: "Full-time",
    description: "Assist in maintaining AWS infrastructure and deployments.",
    track: "Cloud",
    applyUrl: "",
    tags: ["aws", "cloud", "infrastructure"],
    createdBy: "seed"
  },
  {
    title: "AI/ML Research Intern",
    company: "NeuroCore Labs",
    location: "Remote",
    requiredSkills: ["python", "deep learning", "pytorch"],
    recommendedExperience: "Fresher",
    jobType: "Internship",
    description: "Support research team with ML model experiments.",
    track: "AI",
    applyUrl: "",
    tags: ["ai", "ml", "research"],
    createdBy: "seed"
  },
  {
    title: "Junior Game Developer",
    company: "GameNova",
    location: "Dhaka",
    requiredSkills: ["unity", "c#", "game design"],
    recommendedExperience: "Junior",
    jobType: "Full-time",
    description: "Develop gameplay features and optimize performance.",
    track: "Game Development",
    applyUrl: "",
    tags: ["unity", "game dev"],
    createdBy: "seed"
  },
  {
    title: "Senior Web Developer",
    company: "WebMasters",
    location: "Chittagong",
    requiredSkills: ["javascript", "react", "node.js", "architecture"],
    recommendedExperience: "Senior",
    jobType: "Full-time",
    description: "Lead the development of enterprise-level web applications.",
    track: "Web Development",
    applyUrl: "",
    tags: ["senior", "lead", "architecture"],
    createdBy: "seed"
  },
  {
    title: "Junior Network Engineer",
    company: "NetOps BD",
    location: "Dhaka",
    requiredSkills: ["networking", "ccna", "linux"],
    recommendedExperience: "Junior",
    jobType: "Full-time",
    description: "Maintain the organization's network infrastructure.",
    track: "Networking",
    applyUrl: "",
    tags: ["networking", "ccna"],
    createdBy: "seed"
  },
  {
    title: "Freelance Video Editor",
    company: "ViralSpot",
    location: "Remote",
    requiredSkills: ["premiere pro", "editing", "motion graphics"],
    recommendedExperience: "Mid",
    jobType: "Freelance",
    description: "Edit short-form and long-form content for clients.",
    track: "Media",
    applyUrl: "",
    tags: ["video editing", "motion"],
    createdBy: "seed"
  },
  {
    title: "Part-time Social Media Manager",
    company: "BrandBuzz",
    location: "Remote",
    requiredSkills: ["social media", "content creation", "analytics"],
    recommendedExperience: "Junior",
    jobType: "Part-time",
    description: "Manage social media accounts and create engaging posts.",
    track: "Marketing",
    applyUrl: "",
    tags: ["social media", "marketing"],
    createdBy: "seed"
  },
  {
    title: "Junior Robotics Programmer",
    company: "RoboTech BD",
    location: "Dhaka",
    requiredSkills: ["c++", "python", "embedded systems"],
    recommendedExperience: "Junior",
    jobType: "Full-time",
    description: "Develop software modules for robotic systems.",
    track: "Robotics",
    applyUrl: "",
    tags: ["robotics", "embedded"],
    createdBy: "seed"
  }
];
